s3:
  endpoint: http://127.0.0.1:9000
  access-key: minio
  secret-access-key: minio123
  region: "auto"
  max-size-bytes: 107_374_182_400 # 100mb
server:
  address: 0.0.0.0:8080
  read-timeout: 2m
  write-timeout: 1m
  disable-ui: false
logger:
  level: debug
