s3:
  endpoint: 127.0.0.1:9000
  access_key: minio
  secret_access_key: minio123
  region: ""
  signature_type: v4
  disable_delete: false
  disable_force_download: false
  disable_list_recursive: false
iam:
  enabled: false
  endpoint: ""
server:
  address: 127.0.0.1:8080
  read-timeout: 600s
  write-timeout: 600s
sse:
  enabled: false
  type: ""
  key: ""
connection_options:
  skip_ssl: true
  skip_ssl_verification: true
